

trigger: none

pool: mylbpool
   

stages:
  - stage: tfscan
    displayName: tfscan
    jobs:
      - job: tfscan
        continueOnError: true
        displayName: tfscan
        steps:
        - task: tfsec@1
          inputs:
            version: 'v1.26.0'
          continueOnError: true  
        - task: AzureCLI@2
          inputs:
            azureSubscription: 'LB-DEVOPS'
            scriptType: 'bash'
            scriptLocation: 'inlineScript'
            inlineScript: |
                 curl -s https://raw.githubusercontent.com/aquasecurity/tfsec/master/scripts/install_linux.sh | bash

            
                        
        - task: AzureCLI@2
          inputs:
            azureSubscription: 'LB-DEVOPS'
            scriptType: 'bash'
            scriptLocation: 'inlineScript'
            inlineScript: |
                tfsec ./terraform
          continueOnError: true    
                          






            
  - stage: initplan
    dependsOn: tfscan
    displayName: init and plan
    jobs:
      - job: initplan
        displayName: init and plan
        steps:
        - task: TerraformTask@5
          inputs:
            provider: 'azurerm'
            command: 'init'
            workingDirectory: '$(System.DefaultWorkingDirectory)/env/dev'
            backendServiceArm: 'LB-DEVOPS'
            backendAzureRmOverrideSubscriptionID: '75146836-fdff-4091-9190-2ee9cca9c8b6'
            backendAzureRmResourceGroupName: 'shree'
            backendAzureRmStorageAccountName: 'stglb001'
            backendAzureRmContainerName: 'lbcon'
            backendAzureRmKey: 'tf.stetefile'
        - task: TerraformTask@5
          inputs:
            provider: 'azurerm'
            command: 'plan'
            workingDirectory: '$(System.DefaultWorkingDirectory)/env/dev'
            environmentServiceNameAzureRM: 'LB-DEVOPS'
            environmentAzureRmOverrideSubscriptionID: '75146836-fdff-4091-9190-2ee9cca9c8b6'   


  - stage: prvalidation
    displayName: pr
    dependsOn: initplan
    jobs:
      - job: prvalidate
        pool: server
        steps:
        - task: ManualValidation@1
      
          inputs:
            notifyUsers: 'Mahesh.chandra1985@outlook.com'
            approvers: 'Mahesh.chandra1985@outlook.com'
  - stage: terraformapply
    displayName: apply and init
    dependsOn: prvalidation
    jobs:
      - job: intapply
        displayName: init and apply
        steps:
        - task: TerraformTask@5
          inputs:
            provider: 'azurerm'
            command: 'init'
            workingDirectory: '$(System.DefaultWorkingDirectory)/env/dev'
            backendServiceArm: 'LB-DEVOPS'
            backendAzureRmOverrideSubscriptionID: '75146836-fdff-4091-9190-2ee9cca9c8b6'
            backendAzureRmResourceGroupName: 'shree'
            backendAzureRmStorageAccountName: 'stglb001'
            backendAzureRmContainerName: 'lbcon'
            backendAzureRmKey: 'tf.stetefile'
        - task: TerraformTask@5
          inputs:
            provider: 'azurerm'
            command: 'apply'
            workingDirectory: '$(System.DefaultWorkingDirectory)/env/dev'
            commandOptions: '--auto-approve'
            environmentServiceNameAzureRM: 'LB-DEVOPS'
            environmentAzureRmOverrideSubscriptionID: '75146836-fdff-4091-9190-2ee9cca9c8b6'